apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yncf-ik5m-python
  janus-idp.io/tekton: yncf-ik5m-python
  backstage.io/kubernetes-id: yncf-ik5m-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yncf-ik5m-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
