apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yncf-ik5m-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yncf-ik5m-python 
  name: yncf-ik5m-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yncf-ik5m-python 
